/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-spore-b811b00a737247ea9328326a05403ef0
Title: Cyber Spore
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scene.gltf");
  const { actions } = useAnimations(animations, group);

  console.log(materials);

  useEffect(() => {
    actions.Animation.play();
    actions.Animation.timeScale = 0.1;
  }, []);

  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.375}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Torus027_0" scale={0.686}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus028_1" scale={0.686}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus029_2" scale={0.686}>
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus030_3" scale={0.686}>
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus031_4" scale={0.686}>
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus032_5" scale={0.686}>
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus033_6" scale={0.686}>
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus034_7" scale={0.686}>
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus035_8" scale={0.686}>
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus036_9" scale={0.686}>
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus037_10" scale={0.686}>
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus038_11" scale={0.686}>
                <mesh
                  name="Object_26"
                  geometry={nodes.Object_26.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus039_12" scale={0.686}>
                <mesh
                  name="Object_28"
                  geometry={nodes.Object_28.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus040_13" scale={0.686}>
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus041_14" scale={0.686}>
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus042_15" scale={0.686}>
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus043_16" scale={0.686}>
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus044_17" scale={0.686}>
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus045_18" scale={0.686}>
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus046_19" scale={0.686}>
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus047_20" scale={0.686}>
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus048_21" scale={0.686}>
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus049_22" scale={0.686}>
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus050_23" scale={0.686}>
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus051_24" scale={0.686}>
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus001_25" scale={0.854}>
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus002_26" scale={0.854}>
                <mesh
                  name="Object_56"
                  geometry={nodes.Object_56.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus003_27" scale={0.854}>
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus004_28" scale={0.854}>
                <mesh
                  name="Object_60"
                  geometry={nodes.Object_60.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus005_29" scale={0.854}>
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus006_30" scale={0.854}>
                <mesh
                  name="Object_64"
                  geometry={nodes.Object_64.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus007_31" scale={0.854}>
                <mesh
                  name="Object_66"
                  geometry={nodes.Object_66.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus008_32" scale={0.854}>
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus009_33" scale={0.854}>
                <mesh
                  name="Object_70"
                  geometry={nodes.Object_70.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus010_34" scale={0.854}>
                <mesh
                  name="Object_72"
                  geometry={nodes.Object_72.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus011_35" scale={0.854}>
                <mesh
                  name="Object_74"
                  geometry={nodes.Object_74.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus012_36" scale={0.854}>
                <mesh
                  name="Object_76"
                  geometry={nodes.Object_76.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus013_37" scale={0.854}>
                <mesh
                  name="Object_78"
                  geometry={nodes.Object_78.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus014_38" scale={0.854}>
                <mesh
                  name="Object_80"
                  geometry={nodes.Object_80.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus015_39" scale={0.854}>
                <mesh
                  name="Object_82"
                  geometry={nodes.Object_82.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus016_40" scale={0.854}>
                <mesh
                  name="Object_84"
                  geometry={nodes.Object_84.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus017_41" scale={0.854}>
                <mesh
                  name="Object_86"
                  geometry={nodes.Object_86.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus018_42" scale={0.854}>
                <mesh
                  name="Object_88"
                  geometry={nodes.Object_88.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus019_43" scale={0.854}>
                <mesh
                  name="Object_90"
                  geometry={nodes.Object_90.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus020_44" scale={0.854}>
                <mesh
                  name="Object_92"
                  geometry={nodes.Object_92.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus021_45" scale={0.854}>
                <mesh
                  name="Object_94"
                  geometry={nodes.Object_94.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus022_46" scale={0.854}>
                <mesh
                  name="Object_96"
                  geometry={nodes.Object_96.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus023_47" scale={0.854}>
                <mesh
                  name="Object_98"
                  geometry={nodes.Object_98.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus024_48" scale={0.854}>
                <mesh
                  name="Object_100"
                  geometry={nodes.Object_100.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus025_49" scale={0.854}>
                <mesh
                  name="Object_102"
                  geometry={nodes.Object_102.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus026_103" scale={0.425}>
                <mesh
                  name="Object_104"
                  geometry={nodes.Object_104.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus052_104" scale={0.425}>
                <mesh
                  name="Object_106"
                  geometry={nodes.Object_106.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus053_105" scale={0.425}>
                <mesh
                  name="Object_108"
                  geometry={nodes.Object_108.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus054_106" scale={0.425}>
                <mesh
                  name="Object_110"
                  geometry={nodes.Object_110.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus055_107" scale={0.425}>
                <mesh
                  name="Object_112"
                  geometry={nodes.Object_112.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus056_108" scale={0.425}>
                <mesh
                  name="Object_114"
                  geometry={nodes.Object_114.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus057_109" scale={0.425}>
                <mesh
                  name="Object_116"
                  geometry={nodes.Object_116.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus058_110" scale={0.425}>
                <mesh
                  name="Object_118"
                  geometry={nodes.Object_118.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus059_111" scale={0.425}>
                <mesh
                  name="Object_120"
                  geometry={nodes.Object_120.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus060_112" scale={0.425}>
                <mesh
                  name="Object_122"
                  geometry={nodes.Object_122.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus061_113" scale={0.425}>
                <mesh
                  name="Object_124"
                  geometry={nodes.Object_124.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus062_114" scale={0.425}>
                <mesh
                  name="Object_126"
                  geometry={nodes.Object_126.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus063_115" scale={0.425}>
                <mesh
                  name="Object_128"
                  geometry={nodes.Object_128.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus064_116" scale={0.425}>
                <mesh
                  name="Object_130"
                  geometry={nodes.Object_130.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus065_117" scale={0.425}>
                <mesh
                  name="Object_132"
                  geometry={nodes.Object_132.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus066_118" scale={0.425}>
                <mesh
                  name="Object_134"
                  geometry={nodes.Object_134.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus067_119" scale={0.425}>
                <mesh
                  name="Object_136"
                  geometry={nodes.Object_136.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus068_120" scale={0.425}>
                <mesh
                  name="Object_138"
                  geometry={nodes.Object_138.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus069_121" scale={0.425}>
                <mesh
                  name="Object_140"
                  geometry={nodes.Object_140.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus070_122" scale={0.425}>
                <mesh
                  name="Object_142"
                  geometry={nodes.Object_142.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus071_123" scale={0.425}>
                <mesh
                  name="Object_144"
                  geometry={nodes.Object_144.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus072_124" scale={0.425}>
                <mesh
                  name="Object_146"
                  geometry={nodes.Object_146.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus073_125" scale={0.425}>
                <mesh
                  name="Object_148"
                  geometry={nodes.Object_148.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus074_126" scale={0.425}>
                <mesh
                  name="Object_150"
                  geometry={nodes.Object_150.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus075_127" scale={0.425}>
                <mesh
                  name="Object_152"
                  geometry={nodes.Object_152.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus076_128" scale={0.529}>
                <mesh
                  name="Object_154"
                  geometry={nodes.Object_154.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus077_129" scale={0.529}>
                <mesh
                  name="Object_156"
                  geometry={nodes.Object_156.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus078_130" scale={0.529}>
                <mesh
                  name="Object_158"
                  geometry={nodes.Object_158.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus079_131" scale={0.529}>
                <mesh
                  name="Object_160"
                  geometry={nodes.Object_160.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus080_132" scale={0.529}>
                <mesh
                  name="Object_162"
                  geometry={nodes.Object_162.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus081_133" scale={0.529}>
                <mesh
                  name="Object_164"
                  geometry={nodes.Object_164.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus082_134" scale={0.529}>
                <mesh
                  name="Object_166"
                  geometry={nodes.Object_166.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus083_135" scale={0.529}>
                <mesh
                  name="Object_168"
                  geometry={nodes.Object_168.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus084_136" scale={0.529}>
                <mesh
                  name="Object_170"
                  geometry={nodes.Object_170.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus085_137" scale={0.529}>
                <mesh
                  name="Object_172"
                  geometry={nodes.Object_172.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus086_138" scale={0.529}>
                <mesh
                  name="Object_174"
                  geometry={nodes.Object_174.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus087_139" scale={0.529}>
                <mesh
                  name="Object_176"
                  geometry={nodes.Object_176.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus088_140" scale={0.529}>
                <mesh
                  name="Object_178"
                  geometry={nodes.Object_178.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus089_141" scale={0.529}>
                <mesh
                  name="Object_180"
                  geometry={nodes.Object_180.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus090_142" scale={0.529}>
                <mesh
                  name="Object_182"
                  geometry={nodes.Object_182.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus091_143" scale={0.529}>
                <mesh
                  name="Object_184"
                  geometry={nodes.Object_184.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus092_144" scale={0.529}>
                <mesh
                  name="Object_186"
                  geometry={nodes.Object_186.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus093_145" scale={0.529}>
                <mesh
                  name="Object_188"
                  geometry={nodes.Object_188.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus094_146" scale={0.529}>
                <mesh
                  name="Object_190"
                  geometry={nodes.Object_190.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus095_147" scale={0.529}>
                <mesh
                  name="Object_192"
                  geometry={nodes.Object_192.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus096_148" scale={0.529}>
                <mesh
                  name="Object_194"
                  geometry={nodes.Object_194.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus097_149" scale={0.529}>
                <mesh
                  name="Object_196"
                  geometry={nodes.Object_196.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus098_150" scale={0.529}>
                <mesh
                  name="Object_198"
                  geometry={nodes.Object_198.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus099_151" scale={0.529}>
                <mesh
                  name="Object_200"
                  geometry={nodes.Object_200.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus100_152" scale={0.529}>
                <mesh
                  name="Object_202"
                  geometry={nodes.Object_202.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus101_206" scale={0.258}>
                <mesh
                  name="Object_204"
                  geometry={nodes.Object_204.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus102_207" scale={0.258}>
                <mesh
                  name="Object_206"
                  geometry={nodes.Object_206.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus103_208" scale={0.258}>
                <mesh
                  name="Object_208"
                  geometry={nodes.Object_208.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus104_209" scale={0.258}>
                <mesh
                  name="Object_210"
                  geometry={nodes.Object_210.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus105_210" scale={0.258}>
                <mesh
                  name="Object_212"
                  geometry={nodes.Object_212.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus106_211" scale={0.258}>
                <mesh
                  name="Object_214"
                  geometry={nodes.Object_214.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus107_212" scale={0.258}>
                <mesh
                  name="Object_216"
                  geometry={nodes.Object_216.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus108_213" scale={0.258}>
                <mesh
                  name="Object_218"
                  geometry={nodes.Object_218.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus109_214" scale={0.258}>
                <mesh
                  name="Object_220"
                  geometry={nodes.Object_220.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus110_215" scale={0.258}>
                <mesh
                  name="Object_222"
                  geometry={nodes.Object_222.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus111_216" scale={0.258}>
                <mesh
                  name="Object_224"
                  geometry={nodes.Object_224.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus112_217" scale={0.258}>
                <mesh
                  name="Object_226"
                  geometry={nodes.Object_226.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus113_218" scale={0.258}>
                <mesh
                  name="Object_228"
                  geometry={nodes.Object_228.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus114_219" scale={0.258}>
                <mesh
                  name="Object_230"
                  geometry={nodes.Object_230.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus115_220" scale={0.258}>
                <mesh
                  name="Object_232"
                  geometry={nodes.Object_232.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus116_221" scale={0.258}>
                <mesh
                  name="Object_234"
                  geometry={nodes.Object_234.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus117_222" scale={0.258}>
                <mesh
                  name="Object_236"
                  geometry={nodes.Object_236.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus118_223" scale={0.258}>
                <mesh
                  name="Object_238"
                  geometry={nodes.Object_238.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus119_224" scale={0.258}>
                <mesh
                  name="Object_240"
                  geometry={nodes.Object_240.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus120_225" scale={0.258}>
                <mesh
                  name="Object_242"
                  geometry={nodes.Object_242.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus121_226" scale={0.258}>
                <mesh
                  name="Object_244"
                  geometry={nodes.Object_244.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus122_227" scale={0.258}>
                <mesh
                  name="Object_246"
                  geometry={nodes.Object_246.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus123_228" scale={0.258}>
                <mesh
                  name="Object_248"
                  geometry={nodes.Object_248.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus124_229" scale={0.258}>
                <mesh
                  name="Object_250"
                  geometry={nodes.Object_250.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus125_230" scale={0.258}>
                <mesh
                  name="Object_252"
                  geometry={nodes.Object_252.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus126_231" scale={0.321}>
                <mesh
                  name="Object_254"
                  geometry={nodes.Object_254.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus127_232" scale={0.321}>
                <mesh
                  name="Object_256"
                  geometry={nodes.Object_256.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus128_233" scale={0.321}>
                <mesh
                  name="Object_258"
                  geometry={nodes.Object_258.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus129_234" scale={0.321}>
                <mesh
                  name="Object_260"
                  geometry={nodes.Object_260.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus130_235" scale={0.321}>
                <mesh
                  name="Object_262"
                  geometry={nodes.Object_262.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus131_236" scale={0.321}>
                <mesh
                  name="Object_264"
                  geometry={nodes.Object_264.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus132_237" scale={0.321}>
                <mesh
                  name="Object_266"
                  geometry={nodes.Object_266.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus133_238" scale={0.321}>
                <mesh
                  name="Object_268"
                  geometry={nodes.Object_268.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus134_239" scale={0.321}>
                <mesh
                  name="Object_270"
                  geometry={nodes.Object_270.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus135_240" scale={0.321}>
                <mesh
                  name="Object_272"
                  geometry={nodes.Object_272.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus136_241" scale={0.321}>
                <mesh
                  name="Object_274"
                  geometry={nodes.Object_274.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus137_242" scale={0.321}>
                <mesh
                  name="Object_276"
                  geometry={nodes.Object_276.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus138_243" scale={0.321}>
                <mesh
                  name="Object_278"
                  geometry={nodes.Object_278.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus139_244" scale={0.321}>
                <mesh
                  name="Object_280"
                  geometry={nodes.Object_280.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus140_245" scale={0.321}>
                <mesh
                  name="Object_282"
                  geometry={nodes.Object_282.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus141_246" scale={0.321}>
                <mesh
                  name="Object_284"
                  geometry={nodes.Object_284.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus142_247" scale={0.321}>
                <mesh
                  name="Object_286"
                  geometry={nodes.Object_286.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus143_248" scale={0.321}>
                <mesh
                  name="Object_288"
                  geometry={nodes.Object_288.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus144_249" scale={0.321}>
                <mesh
                  name="Object_290"
                  geometry={nodes.Object_290.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus145_250" scale={0.321}>
                <mesh
                  name="Object_292"
                  geometry={nodes.Object_292.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus146_251" scale={0.321}>
                <mesh
                  name="Object_294"
                  geometry={nodes.Object_294.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus147_252" scale={0.321}>
                <mesh
                  name="Object_296"
                  geometry={nodes.Object_296.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus148_253" scale={0.321}>
                <mesh
                  name="Object_298"
                  geometry={nodes.Object_298.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus149_254" scale={0.321}>
                <mesh
                  name="Object_300"
                  geometry={nodes.Object_300.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Torus150_255" scale={0.321}>
                <mesh
                  name="Object_302"
                  geometry={nodes.Object_302.geometry}
                  material={materials["Scene_-_Root"]}
                />
              </group>
              <group name="Circle159_309" scale={14.473} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
